name: CI

on:
  - pull_request

jobs:
  check-pins:
    uses: tnoff/github-workflows/.github/workflows/check-action-pins.yml@67a771844f0c59a3e310920197cc173be4d5805b
  docker:
    name: Docker build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd
    - name: Build image
      uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
      with:
        push: false